{{- if or .Values.services }}
{{- $global := . }}
{{- range $name,$svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
{{- $svcIdentity := default (printf "%s-%s" (include "fullname" $global) $name) $svc.nameOverride}}
  name: {{ $svcIdentity }}
  labels:
    app: {{ include "name" $global }}
    chart: {{ include "chart" $global }}
    release: {{ $global.Release.Name }}
    heritage: {{ $global.Release.Service }}
spec:
{{- with $svc }}
  type: {{ .type }}
  ports:
  {{- if .ports  }}
  {{- range $pName,$p := .ports }}
    - name: {{ printf "%s-%s" $svcIdentity $pName }}
      port: {{ $p.port }}
      {{- if $p.nodePort }}
      nodePort: {{ $p.nodePort }}
      {{- end }}
      protocol: {{ default "TCP" $p.protocol }}
      targetPort: {{printf "%s-%s" $name $pName }}
  {{- end }}
  {{- end }}
{{- end }}
  selector:
    app: {{ include "name" $global }}
    release: {{ $global.Release.Name }}
{{- end }}
{{- end }} # end of range .Values.services